# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 10
cache:
  - npm
  - pip

script:
  - echo "helloworld"

jobs:
  include:
    - stage: Build
      before_script:
        - npm install -g gatsby-cli
      script:
        - cd gatsbys-helloworld
        - ../scripts/build.sh

    - stage: Merge
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh

    - stage: Test
      name: unittest for (gatsby-travis-helloworld)

      script:
        - yarn
        - yarn build

      deploy:
        - provider: pages
          skip_cleanup: true
          script: skip
          local_dir: gatsby-travis-helloworld/public
          github_token: $GITHUB_TOKEN
          on:
            branch: master

      if: branch = master

      after_failure:
        - node -v
        - ls -l gatsby-travis-helloworld
        # - cat /home/travis/.npm/_logs/*.log


stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Integration_to_other_repo
  - Publish_dashboard
  - Merge

import:
  - credentials.yml
  # - gatsby-travis-helloworld/.travis.yml