jobs:
  include:
    - stage: Test
      name: test (gatsby-json-hosting-on-github-tryout)

      script:
        - cd gatsby-json-hosting-on-github-tryout
        -   yarn
        -   yarn build
        - cd -

    - stage: Deploy

      script:
        - cd gatsby-json-hosting-on-github-tryout
        -   yarn
        -   yarn build
        - cd -

      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: gatsby-json-hosting-on-github-tryout/public
          github_token: $GITHUB_TOKEN
          on:
            branch: master
