jobs:
  include:
    - stage: Test
      name: test (gatsby-json-hosting-on-github-tryout)

      script:
        - yarn
        - yarn build

    - stage: Deploy

      script:
        - yarn
        - yarn build

      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: gatsby-json-hosting-on-github-tryout/public
          github_token: $GITHUB_TOKEN
          on:
            branch: master
