# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/box-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/breadcrumb-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/button-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/card-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/content-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/delete-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/dropdown-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/form-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/hero-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/icon-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/images-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/level-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/media-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/menu-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/message-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/modal-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/navbar-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/notifications-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/pagination-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/panel-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/progress-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/table-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/tabs-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/tag-test.js
# git checkout /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/src/components/typography-test.js