jobs:
  include:
    - stage: Build
      name: build (gatsby-helloworld)
      before_script:
        - npm install -g gatsby-cli
      script:
        - cd gatsby-helloworld
        -   yarn
        -   yarn build
        - cd ..
