gatsbyjs-helloworld-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - run: |
        cd gatsbyjs-helloworld-tryout
          test.sh

    - run: |
        cd gatsbyjs-helloworld-tryout
          yarn
          yarn build
