jobs:
  include:
    - stage: Test
      name: unittest for gatsby-travis-helloworld

      script:
        - yarn
        - yarn build

      deploy:
        - provider: pages
          skip_cleanup: true
          script: skip
          local_dir: gatsby-travis-helloworld/public
          github_token: $GITHUB_TOKEN
          on:
            branch: master

      if: branch = master

      after_failure:
        - node -v
        - ls -l gatsby-travis-helloworld
        # - cat /home/travis/.npm/_logs/*.log
