# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12

cache:
  - npm
  - pip

jobs:
  include:
    - stage: Unit_Test
      name: unittest for gatsby-travis-helloworld

      script:
        - yarn
        - yarn build

      deploy:
        - provider: pages
          skip_cleanup: true
          script: skip
          local_dir: gatsby-travis-helloworld/public
          github_token: $GITHUB_TOKEN
          on:
            branch: master

      if: branch = master

      after_failure:
        - node -v
        - ls -l gatsby-travis-helloworld
        # - cat /home/travis/.npm/_logs/*.log
