name: master_build
on:
  push:
  pull_request:

jobs:

  # 
  # /home/logic/_workspace/gatsbyjs-playlist/gatsby-bulmaswatch-tryout/build.yml
  # 
  gatsby-bulmaswatch-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - run: |
          cd gatsby-bulmaswatch-tryout
            yarn
            yarn build
  
  # 
  # /home/logic/_workspace/gatsbyjs-playlist/gatsby-unittest-tryout/build.yml
  # 
  gatsby-unittest-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - run: |
          cd gatsby-unittest-tryout
            yarn
            yarn test
            yarn build
  
  # 
  # /home/logic/_workspace/gatsbyjs-playlist/gatsbyjs-helloworld-tryout/build.yml
  # 
  gatsbyjs-helloworld-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - run: |
          cd gatsbyjs-helloworld-tryout
            yarn
            yarn build
  
  

  # 
  # /home/logic/_workspace/gatsbyjs-playlist/github-build-merger/subjob.yml
  # 
  test_merger:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  
      - name: run test
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          pipenv --help
          github-build-merger/test.sh
  
  merge:
    needs: [gatsby-bulmaswatch-tryout, gatsby-unittest-tryout, gatsbyjs-helloworld-tryout, test_merger]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  
      - name: run merge
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv
  
          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"
  
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
  
          cd github-build-merger
            pipenv sync
  
            pipenv run python3 ./merge.py
          cd ..
  
  
